application: hawkeyepython27
version: 1
runtime: python27
api_version: 1
threadsafe: true

env_variables:
  SHOULD_BE_BAZ: "baz"

builtins:
- deferred: on

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /python/users/secure
  script: main.app
  login: required

- url: /python/secure/always
  script: main.app
  secure: always

- url: /python/secure/always/.*
  script: main.app
  secure: always

- url: /python/secure/never
  script: main.app
  secure: never

- url: /python/secure/never/.*
  script: main.app
  secure: never

- url: /_ah/xmpp/message/chat/?
  script: main.app

- url: /.*
  script: main.app

- url: /python/logserver/(.*)
  script: logservice.py

inbound_services:
- xmpp_message

libraries:
- name: pycrypto
  version: latest
