application: hawkeyepython27
version: 1
runtime: python27
api_version: 1
threadsafe: false

env_variables:
  SHOULD_BE_BAZ: "baz"

builtins:
- deferred: on

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /python/cron.*
  script: cron.py

- url: /python/datastore/(.*)
  script: datastore.py

- url: /python/async_datastore/(.*)
  script: async_datastore.py

- url: /python/ndb/(.*)
  script: ndb.py

- url: /python/memcache.*
  script: memcache.py

- url: /python/taskqueue/(.*)
  script: taskqueue.py

- url: /python/blobstore/(.*)
  script: blobstore.py

- url: /python/users/secure.*
  script: users.py
  login: required

- url: /python/users/(.*)
  script: users.py

- url: /python/images/(.*)
  script: images.py

- url: /python/secure/always
  script: secure_url.py
  secure: always

- url: /python/secure/always/(.*?)/(.*)
  script: secure_url.py
  secure: always

- url: /python/secure/never
  script: secure_url.py
  secure: never

- url: /python/secure/never/(.*?)/(.*)
  script: secure_url.py
  secure: never

- url: /python/env/(.*)
  script: env_var.py

- url: /python/xmpp/?
  script: xmpp.py

- url: /_ah/xmpp/message/chat/?
  script: xmpp.py

- url: /python/search/(.*)
  script: search.py

inbound_services:
- xmpp_message

libraries:
- name: pycrypto
  version: latest
