runtime: python27
api_version: 1
threadsafe: true

env_variables:
  SHOULD_BE_BAZ: "baz"
  SHOULD_HAVE_SPACE: "has space"

includes:
- another_env_var.yaml

builtins:
- deferred: on

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /python/security-1/permissive-1
  script: main.app

- url: /python/security-1/.*
  script: main.app
  secure: always

- url: /python/security-1/permissive-2
  script: main.app

- url: /python/security-2/permissive-1
  script: main.app

- url: /python/security-2/.*
  script: main.app
  secure: never

- url: /python/security-2/permissive-2
  script: main.app

- url: /python/security-3/https-only-1
  script: main.app
  secure: always

- url: /python/security-3/.*
  script: main.app

- url: /python/security-3/https-only-2
  script: main.app
  secure: always

- url: /python/security-4/http-only-1
  script: main.app
  secure: never

- url: /python/security-4/.*
  script: main.app

- url: /python/security-4/http-only-2
  script: main.app
  secure: never

- url: /python/users/secure
  script: main.app
  login: required

- url: /python/secure/always
  script: main.app
  secure: always

- url: /python/secure/always/.*
  script: main.app
  secure: always

- url: /python/secure/never
  script: main.app
  secure: never

- url: /python/secure/never/.*
  script: main.app
  secure: never

- url: /python/taskqueue/admin_worker
  script: main.app
  login: admin

- url: /_ah/xmpp/message/chat/?
  script: main.app

- url: /python/search/(.*)
  script: main.app

- url: /.*
  script: main.app

inbound_services:
- xmpp_message

libraries:
- name: pycrypto
  version: latest
