application: hawkeyepython27
module: warmup
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_ah/warmup
  script: warmup.app
  login: admin

- url: /.*
  script: warmup.app

inbound_services:
- warmup

