application: hawkeyepythonapp
version: 1
runtime: python
api_version: 1
threadsafe: yes

builtins:
- deferred: on

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /python/datastore/(.*)
  script: datastore.py

- url: /python/ndb/(.*)
  script: ndb.py

- url: /python/memcache.*
  script: memcache.py

- url: /python/taskqueue/(.*)
  script: taskqueue.py

- url: /python/blobstore/(.*)
  script: blobstore.py

- url: /python/users/secure.*
  script: users.py
  login: required

- url: /python/users/(.*)
  script: users.py

- url: /python/images/(.*)
  script: images.py